import type { Locale } from '@/lib/constants';

interface ServicePageData {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  icon: string;
  features: { title: string; description: string }[];
  benefits: { bad: string; good: string }[];
  faqs: { question: string; answer: string }[];
}

const servicesData: Record<Locale, Record<string, ServicePageData>> = {
  es: {
    seo: {
      slug: 'seo',
      title: 'SEO',
      metaTitle: 'Agencia SEO Tarragona | Posicionamiento Web Profesional',
      metaDescription: 'Agencia SEO en Tarragona. Posicionamiento web con SEO técnico, contenido optimizado y link building. Resultados medibles y tráfico orgánico cualificado.',
      heroTitle: 'Posiciona tu web en los primeros resultados de Google',
      heroSubtitle: 'Estrategias SEO basadas en datos que generan tráfico orgánico cualificado y conversiones reales.',
      icon: '🔍',
      features: [
        { title: 'SEO Técnico', description: 'Auditoría completa, velocidad de carga, Core Web Vitals, arquitectura web y rastreo.' },
        { title: 'SEO de Contenido', description: 'Investigación de keywords, creación de contenido optimizado y estrategia editorial.' },
        { title: 'Link Building', description: 'Estrategia de enlaces de calidad para aumentar la autoridad de tu dominio.' },
        { title: 'SEO On-Page', description: 'Optimización de títulos, meta descripciones, headers, imágenes y estructura.' },
        { title: 'Analítica SEO', description: 'Seguimiento de posiciones, tráfico orgánico y conversiones con reportes mensuales.' },
        { title: 'SEO Internacional', description: 'Estrategia multiidioma con hreflang, contenido localizado y dominios.' },
      ],
      benefits: [
        { bad: 'Meter keywords a lo loco sin estrategia', good: 'Investigación de keywords con datos reales y estrategia' },
        { bad: 'Comprar enlaces basura que penalizan', good: 'Link building de calidad que sube tu autoridad' },
        { bad: 'Reportes genéricos que no dicen nada', good: 'Reportes con métricas que importan: tráfico, conversiones, ROI' },
        { bad: 'Promesas de "primera posición en 1 mes"', good: 'Resultados reales y sostenibles a medio-largo plazo' },
        { bad: 'Copiar la estrategia de otro cliente', good: 'Estrategia 100% personalizada para tu sector y negocio' },
      ],
      faqs: [
        { question: '¿Cuánto tiempo tarda el SEO en dar resultados?', answer: 'Los primeros resultados se ven entre 3-6 meses, con mejoras constantes. El SEO es una inversión a largo plazo que genera resultados sostenibles.' },
        { question: '¿Qué incluye una auditoría SEO?', answer: 'Analizamos SEO técnico, contenido, perfil de enlaces, competencia, velocidad de carga, Core Web Vitals y oportunidades de keywords.' },
        { question: '¿Cómo medís los resultados del SEO?', answer: 'Utilizamos Google Search Console, Analytics y herramientas profesionales para medir posiciones, tráfico orgánico, conversiones y ROI.' },
        { question: '¿Trabajáis con cualquier tipo de empresa?', answer: 'Nos especializamos en empresas medianas que quieren escalar su presencia online. Trabajamos con e-commerce, SaaS, servicios y negocios locales.' },
      ],
    },
    geo: {
      slug: 'geo',
      title: 'GEO (IA)',
      metaTitle: 'Agencia GEO Tarragona | Posicionamiento en IA (ChatGPT)',
      metaDescription: 'Servicio de GEO en Tarragona. Posiciona tu marca en ChatGPT, Google AI Overviews y Perplexity. Generative Engine Optimization para aparecer en respuestas de IA.',
      heroTitle: 'Aparece en las respuestas de la IA generativa',
      heroSubtitle: 'Optimiza tu presencia para que ChatGPT, Google AI Overviews, Perplexity y otros LLMs recomienden tu marca cuando los usuarios preguntan.',
      icon: '🤖',
      features: [
        { title: 'Optimización para AI Overviews', description: 'Estructura tu contenido para aparecer en las vistas generadas por IA de Google (SGE/AI Overviews).' },
        { title: 'Visibilidad en LLMs', description: 'Estrategias para que ChatGPT, Claude, Gemini y Perplexity mencionen y recomienden tu marca.' },
        { title: 'Contenido citeable', description: 'Creación de contenido autoritativo, estructurado y fácilmente interpretable por modelos de lenguaje.' },
        { title: 'Datos estructurados avanzados', description: 'Schema markup optimizado para que los motores de IA comprendan y citen correctamente tu información.' },
        { title: 'Monitorización de menciones IA', description: 'Seguimiento de cómo los LLMs y motores generativos mencionan tu marca y las de tu competencia.' },
        { title: 'Estrategia E-E-A-T', description: 'Refuerzo de Experiencia, Expertise, Autoridad y Confianza para posicionar en resultados de IA.' },
      ],
      benefits: [
        { bad: 'Ignorar la IA y solo hacer SEO tradicional', good: 'Posicionarte en Google Y en ChatGPT, Perplexity y Gemini' },
        { bad: 'Contenido genérico que la IA no cita', good: 'Contenido autoritativo que los LLMs mencionan y recomiendan' },
        { bad: 'No saber si la IA habla de ti o de la competencia', good: 'Monitorización de menciones en IA con auditorías periódicas' },
        { bad: 'Esperar a que la competencia te adelante', good: 'Ventaja de early adopter en un canal con poca competencia' },
        { bad: 'Web sin datos estructurados que la IA no entiende', good: 'Schema markup avanzado para que la IA cite tu información' },
      ],
      faqs: [
        { question: '¿Qué es GEO (Generative Engine Optimization)?', answer: 'GEO es la optimización de tu presencia digital para aparecer en las respuestas de motores de IA generativa como ChatGPT, Google AI Overviews, Perplexity y Claude. Es la evolución del SEO para la era de la inteligencia artificial.' },
        { question: '¿En qué se diferencia GEO del SEO tradicional?', answer: 'El SEO posiciona en resultados de búsqueda clásicos (enlaces azules). El GEO optimiza para que los LLMs mencionen y recomienden tu marca en sus respuestas generadas por IA. Ambos son complementarios.' },
        { question: '¿Cómo sé si mi marca aparece en ChatGPT o Perplexity?', answer: 'Realizamos auditorías de visibilidad en IA donde probamos consultas relevantes de tu nicho en los principales LLMs y analizamos si tu marca es mencionada, recomendada o ignorada.' },
        { question: '¿Cuánto tarda el GEO en dar resultados?', answer: 'Los LLMs actualizan sus datos periódicamente. Los primeros resultados se ven entre 2-6 meses. La clave es crear contenido autoritativo y estructurado que los modelos aprendan a citar.' },
      ],
    },
    'desarrollo-web': {
      slug: 'desarrollo-web',
      title: 'Desarrollo Web',
      metaTitle: 'Desarrollo Web Tarragona | Diseño Web Profesional a Medida',
      metaDescription: 'Agencia de desarrollo web en Tarragona. Creamos webs rápidas, accesibles y optimizadas para SEO con Next.js y React. Diseño responsive orientado a conversión.',
      heroTitle: 'Webs rápidas, modernas y que convierten',
      heroSubtitle: 'Desarrollo web con las mejores tecnologías: Next.js, React, Tailwind CSS. Rendimiento, accesibilidad y SEO desde el primer día.',
      icon: '🌐',
      features: [
        { title: 'Next.js & React', description: 'Desarrollo con frameworks modernos para máximo rendimiento y experiencia de usuario.' },
        { title: 'Diseño responsive', description: 'Tu web se ve perfecta en móvil, tablet y escritorio. Mobile-first siempre.' },
        { title: 'Optimización de rendimiento', description: 'Lighthouse 95+, Core Web Vitals optimizados y carga ultrarrápida.' },
        { title: 'SEO integrado', description: 'Arquitectura web pensada para SEO desde la primera línea de código.' },
        { title: 'CMS Headless', description: 'Gestión de contenido fácil con CMS headless como Sanity o Contentful.' },
        { title: 'E-commerce', description: 'Tiendas online con Shopify, WooCommerce o soluciones a medida.' },
      ],
      benefits: [
        { bad: 'Web con plantilla genérica igual que mil empresas', good: 'Diseño 100% a medida para tu marca y objetivos' },
        { bad: 'WordPress pesado que tarda 5 segundos en cargar', good: 'Next.js con carga ultrarrápida y Lighthouse 95+' },
        { bad: 'Web bonita pero que no convierte ni posiciona', good: 'Arquitectura pensada para SEO y conversión desde el día 1' },
        { bad: 'Depender de un programador para cada cambio', good: 'CMS fácil para que gestiones tu contenido sin tocar código' },
        { bad: 'Web que se rompe en móvil o tarda en cargar', good: 'Mobile-first, responsive perfecto en cualquier dispositivo' },
      ],
      faqs: [
        { question: '¿Qué tecnologías utilizáis?', answer: 'Trabajamos principalmente con Next.js, React, TypeScript y Tailwind CSS. Elegimos la tecnología según las necesidades de cada proyecto.' },
        { question: '¿Cuánto cuesta una página web?', answer: 'Depende de la complejidad. Una landing page desde 2.000€, una web corporativa desde 5.000€, un e-commerce desde 8.000€. Contacta para un presupuesto preciso.' },
        { question: '¿Cuánto tarda el desarrollo?', answer: 'Una landing page 2-3 semanas, una web corporativa 4-8 semanas, un e-commerce 8-12 semanas. Depende de la complejidad y contenido.' },
        { question: '¿Incluye mantenimiento?', answer: 'Sí, ofrecemos planes de mantenimiento que incluyen actualizaciones, backups, monitorización y soporte técnico.' },
      ],
    },
    'desarrollo-software': {
      slug: 'desarrollo-software',
      title: 'Desarrollo Software',
      metaTitle: 'Desarrollo Software a Medida Tarragona | Apps y APIs',
      metaDescription: 'Empresa de desarrollo de software a medida en Tarragona. APIs, dashboards, integraciones y aplicaciones empresariales. Tecnología que escala con tu negocio.',
      heroTitle: 'Software a medida que escala tu negocio',
      heroSubtitle: 'Desarrollamos aplicaciones, APIs y herramientas empresariales a medida con tecnologías modernas y arquitecturas escalables.',
      icon: '⚙️',
      features: [
        { title: 'APIs y microservicios', description: 'Arquitectura moderna con APIs REST y GraphQL escalables y seguras.' },
        { title: 'Dashboards y paneles', description: 'Visualización de datos en tiempo real para tomar mejores decisiones.' },
        { title: 'Integraciones', description: 'Conexión entre sistemas, CRMs, ERPs y herramientas de terceros.' },
        { title: 'Apps empresariales', description: 'Aplicaciones internas para gestión, inventario, RRHH y procesos.' },
        { title: 'Bases de datos', description: 'Diseño y optimización de bases de datos relacionales y NoSQL.' },
        { title: 'Cloud & DevOps', description: 'Despliegue en la nube con CI/CD, monitorización y escalado automático.' },
      ],
      benefits: [
        { bad: 'Software genérico que no encaja con tu negocio', good: 'Software 100% personalizado para tus procesos exactos' },
        { bad: 'Copy-paste de soluciones de otros clientes', good: 'Desarrollo desde cero pensado para tu caso de uso' },
        { bad: 'Código de terceros del que no eres dueño', good: 'Propiedad total del código: es tuyo para siempre' },
        { bad: 'Sistemas aislados que no hablan entre sí', good: 'Integración con tu CRM, ERP y herramientas existentes' },
        { bad: 'Soluciones que no escalan cuando creces', good: 'Arquitectura escalable que crece contigo sin límites' },
      ],
      faqs: [
        { question: '¿Qué tipo de software desarrolláis?', answer: 'Desarrollamos APIs, dashboards, apps empresariales, integraciones, automatizaciones y cualquier solución de software que necesite tu negocio.' },
        { question: '¿Qué tecnologías usáis para backend?', answer: 'Node.js, Python, Go y bases de datos como PostgreSQL y MongoDB. Elegimos según los requisitos del proyecto.' },
        { question: '¿Ofrecéis mantenimiento del software?', answer: 'Sí, ofrecemos planes de mantenimiento y soporte continuo, incluyendo actualizaciones, monitorización y resolución de incidencias.' },
        { question: '¿Puedo integrar el software con mis herramientas actuales?', answer: 'Por supuesto. Desarrollamos integraciones con CRMs, ERPs, herramientas de marketing, pasarelas de pago y cualquier sistema con API.' },
      ],
    },
    'soluciones-digitales': {
      slug: 'soluciones-digitales',
      title: 'Soluciones Digitales',
      metaTitle: 'Soluciones Digitales para Empresas | Transformación Digital',
      metaDescription: 'Transformación digital para empresas medianas. Consultoría, estrategia e implementación de soluciones digitales que impulsan el crecimiento.',
      heroTitle: 'Transformación digital integral para tu empresa',
      heroSubtitle: 'Desde la estrategia hasta la implementación. Soluciones digitales a medida para empresas que quieren crecer.',
      icon: '💡',
      features: [
        { title: 'Consultoría digital', description: 'Análisis de madurez digital y diseño de hoja de ruta para la transformación.' },
        { title: 'Estrategia digital', description: 'Plan de acción con objetivos, KPIs y presupuesto para tu transformación digital.' },
        { title: 'Marketing digital', description: 'Estrategia de marketing integral: SEO, SEM, redes sociales y email marketing.' },
        { title: 'Analítica y datos', description: 'Implementación de analítica avanzada para decisiones basadas en datos.' },
        { title: 'Experiencia de cliente', description: 'Diseño de customer journeys y optimización de la experiencia digital.' },
        { title: 'Formación digital', description: 'Capacitación de equipos en herramientas y metodologías digitales.' },
      ],
      benefits: [
        { bad: 'Invertir en digital sin estrategia ni rumbo', good: 'Hoja de ruta clara con objetivos y KPIs medibles' },
        { bad: 'Tomar decisiones "a ojo" sin datos', good: 'Decisiones basadas en analítica y datos reales' },
        { bad: 'Cada departamento va por su lado digitalmente', good: 'Estrategia digital integrada en toda la empresa' },
        { bad: 'Experiencia de cliente inconsistente y anticuada', good: 'Customer journey optimizado en todos los puntos de contacto' },
        { bad: 'Formación genérica que no aplica a tu equipo', good: 'Capacitación práctica adaptada a tus herramientas y procesos' },
      ],
      faqs: [
        { question: '¿Qué es la transformación digital?', answer: 'Es el proceso de integrar tecnología digital en todas las áreas de tu negocio, cambiando la forma en que operas y entregas valor a tus clientes.' },
        { question: '¿Por dónde empiezo mi transformación digital?', answer: 'Empezamos con un diagnóstico de madurez digital para entender tu situación actual y diseñar una hoja de ruta personalizada.' },
        { question: '¿Cuánto cuesta la transformación digital?', answer: 'Depende del alcance. Podemos empezar con proyectos pequeños y escalar. Contacta para una consulta gratuita.' },
        { question: '¿Cuánto tiempo toma?', answer: 'La transformación digital es un proceso continuo. Los primeros resultados se ven en 3-6 meses, pero el proceso completo puede llevar 1-2 años.' },
      ],
    },
    automatizaciones: {
      slug: 'automatizaciones',
      title: 'Automatizaciones',
      metaTitle: 'Automatización de Procesos Tarragona | Workflows y Bots',
      metaDescription: 'Automatización de procesos digitales para empresas en Tarragona. Workflows con Make y n8n, bots, integraciones y RPA. Ahorra tiempo y reduce errores.',
      heroTitle: 'Automatiza procesos y libera tu equipo',
      heroSubtitle: 'Eliminamos tareas repetitivas con workflows inteligentes, bots y automatizaciones que ahorran tiempo y reducen errores.',
      icon: '🤖',
      features: [
        { title: 'Workflows automatizados', description: 'Diseño e implementación de flujos de trabajo automatizados con Make, n8n o Zapier.' },
        { title: 'Bots y chatbots', description: 'Bots para atención al cliente, gestión de leads y tareas internas.' },
        { title: 'Email automation', description: 'Secuencias de email automatizadas para nurturing, onboarding y retención.' },
        { title: 'Integración de sistemas', description: 'Conexión automática entre CRM, ERP, facturación y herramientas de equipo.' },
        { title: 'Reporting automatizado', description: 'Informes y dashboards que se generan automáticamente con datos en tiempo real.' },
        { title: 'RPA', description: 'Automatización robótica de procesos para tareas repetitivas y basadas en reglas.' },
      ],
      benefits: [
        { bad: 'Tu equipo perdiendo horas en tareas repetitivas', good: 'Workflows automáticos que trabajan 24/7 sin errores' },
        { bad: 'Errores humanos por copiar datos a mano', good: 'Datos sincronizados automáticamente entre sistemas' },
        { bad: 'Contratar más gente para gestionar más volumen', good: 'Escalar sin aumentar personal gracias a la automatización' },
        { bad: 'Informes manuales que tardan horas en preparar', good: 'Reportes automáticos en tiempo real, listos cada mañana' },
        { bad: 'Equipo quemado haciendo trabajo que una máquina puede hacer', good: 'Tu equipo enfocado en lo que realmente importa' },
      ],
      faqs: [
        { question: '¿Qué procesos se pueden automatizar?', answer: 'Cualquier proceso repetitivo y basado en reglas: envío de emails, gestión de datos, facturación, reporting, onboarding, atención al cliente y más.' },
        { question: '¿Qué herramientas usáis?', answer: 'Usamos Make (Integromat), n8n, Zapier, scripts personalizados y APIs. Elegimos la herramienta según la complejidad y presupuesto.' },
        { question: '¿Cuánto tiempo ahorro con automatización?', answer: 'Depende del proceso, pero nuestros clientes ahorran entre un 40-80% del tiempo dedicado a tareas manuales.' },
        { question: '¿Necesito conocimientos técnicos?', answer: 'No. Diseñamos las automatizaciones para que sean fáciles de mantener y te formamos en su uso.' },
      ],
    },
  },
  en: {
    seo: {
      slug: 'seo',
      title: 'SEO',
      metaTitle: 'SEO Agency Tarragona | Web Positioning',
      metaDescription: 'SEO agency in Tarragona. We improve your web positioning with technical SEO, optimized content and link building. Measurable results from month one.',
      heroTitle: 'Rank your website in Google\'s top results',
      heroSubtitle: 'Data-driven SEO strategies that generate qualified organic traffic and real conversions.',
      icon: '🔍',
      features: [
        { title: 'Technical SEO', description: 'Complete audit, load speed, Core Web Vitals, web architecture and crawling.' },
        { title: 'Content SEO', description: 'Keyword research, optimized content creation and editorial strategy.' },
        { title: 'Link Building', description: 'Quality link strategy to increase your domain authority.' },
        { title: 'On-Page SEO', description: 'Title optimization, meta descriptions, headers, images and structure.' },
        { title: 'SEO Analytics', description: 'Position tracking, organic traffic and conversions with monthly reports.' },
        { title: 'International SEO', description: 'Multilingual strategy with hreflang, localized content and domains.' },
      ],
      benefits: [
        { bad: 'Stuffing keywords randomly without strategy', good: 'Data-driven keyword research with a real strategy' },
        { bad: 'Buying spammy links that get you penalized', good: 'Quality link building that grows your authority' },
        { bad: 'Generic reports that say nothing useful', good: 'Reports with metrics that matter: traffic, conversions, ROI' },
        { bad: 'Promising "first position in 1 month"', good: 'Real, sustainable results over the medium-long term' },
        { bad: 'Copy-pasting another client\'s strategy', good: '100% customized strategy for your industry and business' },
      ],
      faqs: [
        { question: 'How long does SEO take to show results?', answer: 'First results are seen between 3-6 months, with constant improvements. SEO is a long-term investment that generates sustainable results.' },
        { question: 'What does an SEO audit include?', answer: 'We analyze technical SEO, content, link profile, competition, load speed, Core Web Vitals and keyword opportunities.' },
        { question: 'How do you measure SEO results?', answer: 'We use Google Search Console, Analytics and professional tools to measure positions, organic traffic, conversions and ROI.' },
        { question: 'Do you work with any type of business?', answer: 'We specialize in mid-sized companies looking to scale their online presence. We work with e-commerce, SaaS, services and local businesses.' },
      ],
    },
    geo: {
      slug: 'geo',
      title: 'GEO (AI)',
      metaTitle: 'GEO Agency Tarragona | AI & LLM Positioning',
      metaDescription: 'GEO (Generative Engine Optimization) service in Tarragona. Position your brand in ChatGPT, Google AI Overviews, Perplexity and generative AI engines.',
      heroTitle: 'Appear in generative AI answers',
      heroSubtitle: 'Optimize your presence so ChatGPT, Google AI Overviews, Perplexity and other LLMs recommend your brand when users ask.',
      icon: '🤖',
      features: [
        { title: 'AI Overviews Optimization', description: 'Structure your content to appear in Google\'s AI-generated views (SGE/AI Overviews).' },
        { title: 'LLM Visibility', description: 'Strategies for ChatGPT, Claude, Gemini and Perplexity to mention and recommend your brand.' },
        { title: 'Citable Content', description: 'Authoritative, structured content easily interpretable by language models.' },
        { title: 'Advanced Structured Data', description: 'Optimized schema markup so AI engines correctly understand and cite your information.' },
        { title: 'AI Mention Monitoring', description: 'Track how LLMs and generative engines mention your brand vs. competitors.' },
        { title: 'E-E-A-T Strategy', description: 'Strengthen Experience, Expertise, Authority and Trust to rank in AI results.' },
      ],
      benefits: [
        { bad: 'Ignoring AI and only doing traditional SEO', good: 'Rank on Google AND in ChatGPT, Perplexity and Gemini' },
        { bad: 'Generic content that AI never cites', good: 'Authoritative content that LLMs mention and recommend' },
        { bad: 'Not knowing if AI talks about you or competitors', good: 'AI mention monitoring with periodic audits' },
        { bad: 'Waiting until competitors get ahead', good: 'Early adopter advantage in a low-competition channel' },
        { bad: 'Website without structured data that AI can\'t understand', good: 'Advanced schema markup so AI cites your information' },
      ],
      faqs: [
        { question: 'What is GEO (Generative Engine Optimization)?', answer: 'GEO is the optimization of your digital presence to appear in responses from generative AI engines like ChatGPT, Google AI Overviews, Perplexity and Claude. It is the evolution of SEO for the artificial intelligence era.' },
        { question: 'How is GEO different from traditional SEO?', answer: 'SEO positions you in classic search results (blue links). GEO optimizes so LLMs mention and recommend your brand in their AI-generated answers. Both are complementary.' },
        { question: 'How do I know if my brand appears in ChatGPT or Perplexity?', answer: 'We conduct AI visibility audits where we test relevant queries in your niche across major LLMs and analyze whether your brand is mentioned, recommended or ignored.' },
        { question: 'How long does GEO take to show results?', answer: 'LLMs update their data periodically. First results are seen between 2-6 months. The key is creating authoritative, structured content that models learn to cite.' },
      ],
    },
    'desarrollo-web': {
      slug: 'web-development',
      title: 'Web Development',
      metaTitle: 'Web Development Tarragona | Professional Websites',
      metaDescription: 'Professional web development in Tarragona. Fast, accessible and optimized websites with Next.js and React. Responsive design and conversion-oriented.',
      heroTitle: 'Fast, modern websites that convert',
      heroSubtitle: 'Web development with the best technologies: Next.js, React, Tailwind CSS. Performance, accessibility and SEO from day one.',
      icon: '🌐',
      features: [
        { title: 'Next.js & React', description: 'Development with modern frameworks for maximum performance and user experience.' },
        { title: 'Responsive Design', description: 'Your website looks perfect on mobile, tablet and desktop. Always mobile-first.' },
        { title: 'Performance Optimization', description: 'Lighthouse 95+, optimized Core Web Vitals and ultra-fast loading.' },
        { title: 'Integrated SEO', description: 'Web architecture designed for SEO from the first line of code.' },
        { title: 'Headless CMS', description: 'Easy content management with headless CMS like Sanity or Contentful.' },
        { title: 'E-commerce', description: 'Online stores with Shopify, WooCommerce or custom solutions.' },
      ],
      benefits: [
        { bad: 'Generic template website like a thousand others', good: '100% custom design for your brand and goals' },
        { bad: 'Heavy WordPress that takes 5 seconds to load', good: 'Next.js with ultra-fast loading and Lighthouse 95+' },
        { bad: 'Pretty website that doesn\'t convert or rank', good: 'Architecture built for SEO and conversion from day 1' },
        { bad: 'Depending on a developer for every small change', good: 'Easy CMS so you manage content without touching code' },
        { bad: 'Website that breaks on mobile or loads slowly', good: 'Mobile-first, perfect responsive on any device' },
      ],
      faqs: [
        { question: 'What technologies do you use?', answer: 'We mainly work with Next.js, React, TypeScript and Tailwind CSS. We choose the technology based on each project\'s needs.' },
        { question: 'How much does a website cost?', answer: 'It depends on complexity. A landing page from €2,000, a corporate website from €5,000, an e-commerce from €8,000. Contact for an exact quote.' },
        { question: 'How long does development take?', answer: 'A landing page 2-3 weeks, a corporate website 4-8 weeks, an e-commerce 8-12 weeks. Depends on complexity and content.' },
        { question: 'Does it include maintenance?', answer: 'Yes, we offer maintenance plans that include updates, backups, monitoring and technical support.' },
      ],
    },
    'desarrollo-software': {
      slug: 'software-development',
      title: 'Software Development',
      metaTitle: 'Custom Software Development | Tarragona',
      metaDescription: 'Custom software development in Tarragona. APIs, dashboards, integrations and enterprise applications. Technology that scales with your business.',
      heroTitle: 'Custom software that scales your business',
      heroSubtitle: 'We develop applications, APIs and custom enterprise tools with modern technologies and scalable architectures.',
      icon: '⚙️',
      features: [
        { title: 'APIs & Microservices', description: 'Modern architecture with scalable and secure REST and GraphQL APIs.' },
        { title: 'Dashboards & Panels', description: 'Real-time data visualization for better decision making.' },
        { title: 'Integrations', description: 'Connection between systems, CRMs, ERPs and third-party tools.' },
        { title: 'Enterprise Apps', description: 'Internal applications for management, inventory, HR and processes.' },
        { title: 'Databases', description: 'Design and optimization of relational and NoSQL databases.' },
        { title: 'Cloud & DevOps', description: 'Cloud deployment with CI/CD, monitoring and auto-scaling.' },
      ],
      benefits: [
        { bad: 'Generic software that doesn\'t fit your business', good: '100% custom software for your exact processes' },
        { bad: 'Copy-pasting solutions from other clients', good: 'Built from scratch for your specific use case' },
        { bad: 'Third-party code you don\'t own', good: 'Full code ownership: it\'s yours forever' },
        { bad: 'Isolated systems that don\'t talk to each other', good: 'Integration with your CRM, ERP and existing tools' },
        { bad: 'Solutions that don\'t scale when you grow', good: 'Scalable architecture that grows with you' },
      ],
      faqs: [
        { question: 'What type of software do you develop?', answer: 'We develop APIs, dashboards, enterprise apps, integrations, automations and any software solution your business needs.' },
        { question: 'What backend technologies do you use?', answer: 'Node.js, Python, Go and databases like PostgreSQL and MongoDB. We choose based on project requirements.' },
        { question: 'Do you offer software maintenance?', answer: 'Yes, we offer maintenance and continuous support plans, including updates, monitoring and incident resolution.' },
        { question: 'Can I integrate the software with my current tools?', answer: 'Absolutely. We develop integrations with CRMs, ERPs, marketing tools, payment gateways and any system with an API.' },
      ],
    },
    'soluciones-digitales': {
      slug: 'digital-solutions',
      title: 'Digital Solutions',
      metaTitle: 'Digital Solutions for Business | Digital Transformation',
      metaDescription: 'Digital transformation for mid-sized companies. Consulting, strategy and implementation of digital solutions that drive growth.',
      heroTitle: 'End-to-end digital transformation for your business',
      heroSubtitle: 'From strategy to implementation. Custom digital solutions for businesses that want to grow.',
      icon: '💡',
      features: [
        { title: 'Digital Consulting', description: 'Digital maturity analysis and transformation roadmap design.' },
        { title: 'Digital Strategy', description: 'Action plan with objectives, KPIs and budget for your digital transformation.' },
        { title: 'Digital Marketing', description: 'Comprehensive marketing strategy: SEO, SEM, social media and email marketing.' },
        { title: 'Analytics & Data', description: 'Advanced analytics implementation for data-driven decisions.' },
        { title: 'Customer Experience', description: 'Customer journey design and digital experience optimization.' },
        { title: 'Digital Training', description: 'Team training in digital tools and methodologies.' },
      ],
      benefits: [
        { bad: 'Investing in digital with no strategy or direction', good: 'Clear roadmap with measurable objectives and KPIs' },
        { bad: 'Making decisions "by gut feeling" without data', good: 'Decisions based on analytics and real data' },
        { bad: 'Each department going its own way digitally', good: 'Integrated digital strategy across the whole company' },
        { bad: 'Inconsistent, outdated customer experience', good: 'Optimized customer journey at every touchpoint' },
        { bad: 'Generic training that doesn\'t apply to your team', good: 'Practical training adapted to your tools and processes' },
      ],
      faqs: [
        { question: 'What is digital transformation?', answer: 'It is the process of integrating digital technology across all areas of your business, changing how you operate and deliver value to your customers.' },
        { question: 'Where do I start my digital transformation?', answer: 'We start with a digital maturity diagnosis to understand your current situation and design a personalized roadmap.' },
        { question: 'How much does digital transformation cost?', answer: 'It depends on scope. We can start with small projects and scale. Contact us for a free consultation.' },
        { question: 'How long does it take?', answer: 'Digital transformation is an ongoing process. First results are seen in 3-6 months, but the full process can take 1-2 years.' },
      ],
    },
    automatizaciones: {
      slug: 'automations',
      title: 'Automations',
      metaTitle: 'Business Process Automation | Tarragona',
      metaDescription: 'Process automation for businesses. Workflows, bots, integrations and RPA. Save time and reduce errors with intelligent automation.',
      heroTitle: 'Automate processes and free your team',
      heroSubtitle: 'We eliminate repetitive tasks with intelligent workflows, bots and automations that save time and reduce errors.',
      icon: '🤖',
      features: [
        { title: 'Automated Workflows', description: 'Design and implementation of automated workflows with Make, n8n or Zapier.' },
        { title: 'Bots & Chatbots', description: 'Bots for customer service, lead management and internal tasks.' },
        { title: 'Email Automation', description: 'Automated email sequences for nurturing, onboarding and retention.' },
        { title: 'System Integration', description: 'Automatic connection between CRM, ERP, billing and team tools.' },
        { title: 'Automated Reporting', description: 'Reports and dashboards that are automatically generated with real-time data.' },
        { title: 'RPA', description: 'Robotic process automation for repetitive and rule-based tasks.' },
      ],
      benefits: [
        { bad: 'Your team wasting hours on repetitive tasks', good: 'Automated workflows that work 24/7 without errors' },
        { bad: 'Human errors from copying data by hand', good: 'Data synced automatically between systems' },
        { bad: 'Hiring more people to handle more volume', good: 'Scale without increasing staff thanks to automation' },
        { bad: 'Manual reports that take hours to prepare', good: 'Automatic real-time reports, ready every morning' },
        { bad: 'Team burned out doing work a machine can do', good: 'Your team focused on what truly matters' },
      ],
      faqs: [
        { question: 'What processes can be automated?', answer: 'Any repetitive and rule-based process: email sending, data management, billing, reporting, onboarding, customer service and more.' },
        { question: 'What tools do you use?', answer: 'We use Make (Integromat), n8n, Zapier, custom scripts and APIs. We choose the tool based on complexity and budget.' },
        { question: 'How much time do I save with automation?', answer: 'It depends on the process, but our clients save between 40-80% of time spent on manual tasks.' },
        { question: 'Do I need technical knowledge?', answer: 'No. We design automations to be easy to maintain and train you on their use.' },
      ],
    },
  },
  ca: {
    seo: {
      slug: 'seo',
      title: 'SEO',
      metaTitle: 'Agència SEO Tarragona | Posicionament Web',
      metaDescription: 'Agència SEO a Tarragona. Millorem el teu posicionament web amb SEO tècnic, contingut optimitzat i link building.',
      heroTitle: 'Posiciona el teu web als primers resultats de Google',
      heroSubtitle: 'Estratègies SEO basades en dades que generen tràfic orgànic qualificat i conversions reals.',
      icon: '🔍',
      features: [
        { title: 'SEO Tècnic', description: 'Auditoria completa, velocitat de càrrega, Core Web Vitals, arquitectura web i rastreig.' },
        { title: 'SEO de Contingut', description: 'Investigació de keywords, creació de contingut optimitzat i estratègia editorial.' },
        { title: 'Link Building', description: 'Estratègia d\'enllaços de qualitat per augmentar l\'autoritat del teu domini.' },
        { title: 'SEO On-Page', description: 'Optimització de títols, meta descripcions, headers, imatges i estructura.' },
        { title: 'Analítica SEO', description: 'Seguiment de posicions, tràfic orgànic i conversions amb informes mensuals.' },
        { title: 'SEO Internacional', description: 'Estratègia multiidioma amb hreflang, contingut localitzat i dominis.' },
      ],
      benefits: [
        { bad: 'Ficar keywords a lo boig sense estratègia', good: 'Investigació de keywords amb dades reals i estratègia' },
        { bad: 'Comprar enllaços brossa que penalitzen', good: 'Link building de qualitat que puja la teva autoritat' },
        { bad: 'Informes genèrics que no diuen res', good: 'Informes amb mètriques que importen: tràfic, conversions, ROI' },
        { bad: 'Promeses de "primera posició en 1 mes"', good: 'Resultats reals i sostenibles a mig-llarg termini' },
        { bad: 'Copiar l\'estratègia d\'un altre client', good: 'Estratègia 100% personalitzada per al teu sector i negoci' },
      ],
      faqs: [
        { question: 'Quant de temps tarda el SEO a donar resultats?', answer: 'Els primers resultats es veuen entre 3-6 mesos, amb millores constants. El SEO és una inversió a llarg termini.' },
        { question: 'Què inclou una auditoria SEO?', answer: 'Analitzem SEO tècnic, contingut, perfil d\'enllaços, competència, velocitat de càrrega i oportunitats de keywords.' },
        { question: 'Com mesureu els resultats del SEO?', answer: 'Utilitzem Google Search Console, Analytics i eines professionals per mesurar posicions, tràfic orgànic, conversions i ROI.' },
        { question: 'Treballeu amb qualsevol tipus d\'empresa?', answer: 'Ens especialitzem en empreses mitjanes que volen escalar la seva presència online.' },
      ],
    },
    geo: {
      slug: 'geo',
      title: 'GEO (IA)',
      metaTitle: 'Agència GEO Tarragona | Posicionament en IA i LLMs',
      metaDescription: 'Servei de GEO (Generative Engine Optimization) a Tarragona. Posiciona la teva marca a ChatGPT, Google AI Overviews, Perplexity i motors d\'IA generativa.',
      heroTitle: 'Apareix a les respostes de la IA generativa',
      heroSubtitle: 'Optimitza la teva presència perquè ChatGPT, Google AI Overviews, Perplexity i altres LLMs recomanin la teva marca.',
      icon: '🤖',
      features: [
        { title: 'Optimització per AI Overviews', description: 'Estructura el teu contingut per aparèixer a les vistes generades per IA de Google.' },
        { title: 'Visibilitat en LLMs', description: 'Estratègies perquè ChatGPT, Claude, Gemini i Perplexity esmentin la teva marca.' },
        { title: 'Contingut citable', description: 'Creació de contingut autoritatiu i estructurat fàcilment interpretable per models de llenguatge.' },
        { title: 'Dades estructurades avançades', description: 'Schema markup optimitzat perquè els motors d\'IA comprenguin i citin la teva informació.' },
        { title: 'Monitorització de mencions IA', description: 'Seguiment de com els LLMs i motors generatius esmenten la teva marca.' },
        { title: 'Estratègia E-E-A-T', description: 'Reforç d\'Experiència, Expertise, Autoritat i Confiança per posicionar en resultats d\'IA.' },
      ],
      benefits: [
        { bad: 'Ignorar la IA i només fer SEO tradicional', good: 'Posicionar-te a Google I a ChatGPT, Perplexity i Gemini' },
        { bad: 'Contingut genèric que la IA no cita', good: 'Contingut autoritatiu que els LLMs esmenten i recomanen' },
        { bad: 'No saber si la IA parla de tu o de la competència', good: 'Monitorització de mencions en IA amb auditories periòdiques' },
        { bad: 'Esperar que la competència et passi al davant', good: 'Avantatge d\'early adopter en un canal amb poca competència' },
        { bad: 'Web sense dades estructurades que la IA no entén', good: 'Schema markup avançat perquè la IA citi la teva informació' },
      ],
      faqs: [
        { question: 'Què és GEO (Generative Engine Optimization)?', answer: 'GEO és l\'optimització de la teva presència digital per aparèixer a les respostes de motors d\'IA generativa com ChatGPT, Google AI Overviews i Perplexity.' },
        { question: 'En què es diferencia GEO del SEO tradicional?', answer: 'El SEO posiciona en resultats de cerca clàssics. El GEO optimitza perquè els LLMs esmentin i recomanin la teva marca a les seves respostes generades per IA.' },
        { question: 'Com sé si la meva marca apareix a ChatGPT?', answer: 'Realitzem auditories de visibilitat en IA on provem consultes rellevants del teu nínxol als principals LLMs.' },
        { question: 'Quant tarda el GEO a donar resultats?', answer: 'Els LLMs actualitzen les seves dades periòdicament. Els primers resultats es veuen entre 2-6 mesos.' },
      ],
    },
    'desarrollo-web': {
      slug: 'desenvolupament-web',
      title: 'Desenvolupament Web',
      metaTitle: 'Desenvolupament Web Tarragona | Pàgines Web Professionals',
      metaDescription: 'Desenvolupament web professional a Tarragona. Webs ràpides, accessibles i optimitzades amb Next.js i React.',
      heroTitle: 'Webs ràpides, modernes i que converteixen',
      heroSubtitle: 'Desenvolupament web amb les millors tecnologies: Next.js, React, Tailwind CSS.',
      icon: '🌐',
      features: [
        { title: 'Next.js & React', description: 'Desenvolupament amb frameworks moderns per al màxim rendiment.' },
        { title: 'Disseny responsive', description: 'El teu web es veu perfecte en mòbil, tauleta i escriptori.' },
        { title: 'Optimització de rendiment', description: 'Lighthouse 95+, Core Web Vitals optimitzats.' },
        { title: 'SEO integrat', description: 'Arquitectura web pensada per a SEO des de la primera línia de codi.' },
        { title: 'CMS Headless', description: 'Gestió de contingut fàcil amb CMS headless.' },
        { title: 'E-commerce', description: 'Botigues online amb Shopify, WooCommerce o solucions a mida.' },
      ],
      benefits: [
        { bad: 'Web amb plantilla genèrica igual que mil empreses', good: 'Disseny 100% a mida per a la teva marca i objectius' },
        { bad: 'WordPress pesat que tarda 5 segons a carregar', good: 'Next.js amb càrrega ultraràpida i Lighthouse 95+' },
        { bad: 'Web bonica però que no converteix ni posiciona', good: 'Arquitectura pensada per a SEO i conversió des del dia 1' },
        { bad: 'Dependre d\'un programador per cada canvi', good: 'CMS fàcil perquè gestionis el teu contingut sense tocar codi' },
        { bad: 'Web que es trenca al mòbil o tarda a carregar', good: 'Mobile-first, responsive perfecte en qualsevol dispositiu' },
      ],
      faqs: [
        { question: 'Quines tecnologies utilitzeu?', answer: 'Treballem principalment amb Next.js, React, TypeScript i Tailwind CSS.' },
        { question: 'Quant costa una pàgina web?', answer: 'Depèn de la complexitat. Landing page des de 2.000€, web corporativa des de 5.000€, e-commerce des de 8.000€.' },
        { question: 'Quant tarda el desenvolupament?', answer: 'Landing page 2-3 setmanes, web corporativa 4-8 setmanes, e-commerce 8-12 setmanes.' },
        { question: 'Inclou manteniment?', answer: 'Sí, oferim plans de manteniment amb actualitzacions, backups i suport tècnic.' },
      ],
    },
    'desarrollo-software': {
      slug: 'desenvolupament-software',
      title: 'Desenvolupament Software',
      metaTitle: 'Desenvolupament Software a Mida | Tarragona',
      metaDescription: 'Desenvolupament de software a mida a Tarragona. APIs, dashboards, integracions i aplicacions empresarials.',
      heroTitle: 'Software a mida que escala el teu negoci',
      heroSubtitle: 'Desenvolupem aplicacions, APIs i eines empresarials a mida.',
      icon: '⚙️',
      features: [
        { title: 'APIs i microserveis', description: 'Arquitectura moderna amb APIs REST i GraphQL escalables.' },
        { title: 'Dashboards i panells', description: 'Visualització de dades en temps real.' },
        { title: 'Integracions', description: 'Connexió entre sistemes, CRMs, ERPs i eines de tercers.' },
        { title: 'Apps empresarials', description: 'Aplicacions internes per a gestió, inventari i processos.' },
        { title: 'Bases de dades', description: 'Disseny i optimització de bases de dades relacionals i NoSQL.' },
        { title: 'Cloud & DevOps', description: 'Desplegament al núvol amb CI/CD i monitorització.' },
      ],
      benefits: [
        { bad: 'Software genèric que no encaixa amb el teu negoci', good: 'Software 100% personalitzat per als teus processos exactes' },
        { bad: 'Copy-paste de solucions d\'altres clients', good: 'Desenvolupament des de zero pensat per al teu cas d\'ús' },
        { bad: 'Codi de tercers del que no ets propietari', good: 'Propietat total del codi: és teu per sempre' },
        { bad: 'Sistemes aïllats que no parlen entre ells', good: 'Integració amb el teu CRM, ERP i eines existents' },
        { bad: 'Solucions que no escalen quan creixes', good: 'Arquitectura escalable que creix amb tu sense límits' },
      ],
      faqs: [
        { question: 'Quin tipus de software desenvolupeu?', answer: 'APIs, dashboards, apps empresarials, integracions, automatitzacions i qualsevol solució de software.' },
        { question: 'Quines tecnologies useu per backend?', answer: 'Node.js, Python, Go i bases de dades com PostgreSQL i MongoDB.' },
        { question: 'Oferiu manteniment del software?', answer: 'Sí, oferim plans de manteniment i suport continu.' },
        { question: 'Puc integrar el software amb les meves eines actuals?', answer: 'Per descomptat. Desenvolupem integracions amb CRMs, ERPs i qualsevol sistema amb API.' },
      ],
    },
    'soluciones-digitales': {
      slug: 'solucions-digitals',
      title: 'Solucions Digitals',
      metaTitle: 'Solucions Digitals per a Empreses | Transformació Digital',
      metaDescription: 'Transformació digital per a empreses mitjanes. Consultoria, estratègia i implementació de solucions digitals.',
      heroTitle: 'Transformació digital integral per a la teva empresa',
      heroSubtitle: 'Des de l\'estratègia fins a la implementació. Solucions digitals a mida.',
      icon: '💡',
      features: [
        { title: 'Consultoria digital', description: 'Anàlisi de maduresa digital i disseny de full de ruta.' },
        { title: 'Estratègia digital', description: 'Pla d\'acció amb objectius, KPIs i pressupost.' },
        { title: 'Màrqueting digital', description: 'Estratègia integral: SEO, SEM, xarxes socials i email marketing.' },
        { title: 'Analítica i dades', description: 'Implementació d\'analítica avançada per a decisions basades en dades.' },
        { title: 'Experiència de client', description: 'Disseny de customer journeys i optimització de l\'experiència digital.' },
        { title: 'Formació digital', description: 'Capacitació d\'equips en eines i metodologies digitals.' },
      ],
      benefits: [
        { bad: 'Invertir en digital sense estratègia ni rumb', good: 'Full de ruta clar amb objectius i KPIs mesurables' },
        { bad: 'Prendre decisions "a ull" sense dades', good: 'Decisions basades en analítica i dades reals' },
        { bad: 'Cada departament va per la seva digitalment', good: 'Estratègia digital integrada a tota l\'empresa' },
        { bad: 'Experiència de client inconsistent i antiquada', good: 'Customer journey optimitzat en tots els punts de contacte' },
        { bad: 'Formació genèrica que no aplica al teu equip', good: 'Capacitació pràctica adaptada a les teves eines i processos' },
      ],
      faqs: [
        { question: 'Què és la transformació digital?', answer: 'És el procés d\'integrar tecnologia digital en totes les àrees del teu negoci.' },
        { question: 'Per on començo?', answer: 'Comencem amb un diagnòstic de maduresa digital per entendre la teva situació actual.' },
        { question: 'Quant costa?', answer: 'Depèn de l\'abast. Podem començar amb projectes petits i escalar.' },
        { question: 'Quant de temps pren?', answer: 'Els primers resultats es veuen en 3-6 mesos, però el procés complet pot portar 1-2 anys.' },
      ],
    },
    automatizaciones: {
      slug: 'automatitzacions',
      title: 'Automatitzacions',
      metaTitle: 'Automatització de Processos Empresarials | Tarragona',
      metaDescription: 'Automatització de processos per a empreses. Workflows, bots, integracions i RPA.',
      heroTitle: 'Automatitza processos i allibera el teu equip',
      heroSubtitle: 'Eliminem tasques repetitives amb workflows intel·ligents, bots i automatitzacions.',
      icon: '🤖',
      features: [
        { title: 'Workflows automatitzats', description: 'Disseny i implementació de fluxos de treball automatitzats.' },
        { title: 'Bots i chatbots', description: 'Bots per a atenció al client, gestió de leads i tasques internes.' },
        { title: 'Email automation', description: 'Seqüències d\'email automatitzades per a nurturing i retenció.' },
        { title: 'Integració de sistemes', description: 'Connexió automàtica entre CRM, ERP, facturació i eines d\'equip.' },
        { title: 'Reporting automatitzat', description: 'Informes que es generen automàticament amb dades en temps real.' },
        { title: 'RPA', description: 'Automatització robòtica de processos per a tasques repetitives.' },
      ],
      benefits: [
        { bad: 'El teu equip perdent hores en tasques repetitives', good: 'Workflows automàtics que treballen 24/7 sense errors' },
        { bad: 'Errors humans per copiar dades a mà', good: 'Dades sincronitzades automàticament entre sistemes' },
        { bad: 'Contractar més gent per gestionar més volum', good: 'Escalar sense augmentar personal gràcies a l\'automatització' },
        { bad: 'Informes manuals que triguen hores a preparar', good: 'Informes automàtics en temps real, llestos cada matí' },
        { bad: 'Equip cremat fent feina que una màquina pot fer', good: 'El teu equip enfocat en el que realment importa' },
      ],
      faqs: [
        { question: 'Quins processos es poden automatitzar?', answer: 'Qualsevol procés repetitiu: enviament d\'emails, gestió de dades, facturació, reporting i més.' },
        { question: 'Quines eines useu?', answer: 'Make, n8n, Zapier, scripts personalitzats i APIs.' },
        { question: 'Quant de temps estalvio?', answer: 'Els nostres clients estalvien entre un 40-80% del temps dedicat a tasques manuals.' },
        { question: 'Necessito coneixements tècnics?', answer: 'No. Dissenyem les automatitzacions per ser fàcils de mantenir.' },
      ],
    },
  },
};

export function getServiceData(locale: Locale, slug: string): ServicePageData | null {
  // First try direct key lookup
  if (servicesData[locale]?.[slug]) return servicesData[locale][slug];
  // Then try matching by translated slug
  const entries = Object.values(servicesData[locale] || {});
  return entries.find((s) => s.slug === slug) || null;
}

export function getAllServiceSlugs(): string[] {
  const locales: Locale[] = ['es', 'en', 'ca'];
  const slugs = new Set<string>();
  for (const locale of locales) {
    for (const service of Object.values(servicesData[locale])) {
      slugs.add(service.slug);
    }
  }
  return Array.from(slugs);
}
